# Running fitting with LSDB

Use `Catalog.map_rows` to run fitting with two bands.

In [1]:
import jax
import jax.numpy as jnp
import lsdb
import nested_pandas as npd
import numpy as np

from distributed import Client
from eztaox.kernels.quasisep import Exp
from eztaox.fitter import random_search
from eztaox.models import MultiVarModel

Read object test data with light curves:

In [2]:
df = npd.read_parquet("data/lightcurve_thindisk_fixed_nested.parquet")
cols = [c for c in df.columns if c not in ["transfer_function"]]
df = df[cols]
df

    ID  cos_inc  log_mbh  log_mdot  redshift  \
0    0    0.866      8.0       0.0       0.1
1    1    0.866      8.0       0.0       0.1
..  ..      ...      ...       ...       ...
98  98    0.866      8.0       0.0       0.1
99  99    0.866      8.0       0.0       0.1

                                                  lag  \
0   [2.18424467 2.97357418 4.20083785 5.36442491 6...
1   [2.18424467 2.97357418 4.20083785 5.36442491 6...
..                                                ...
98  [2.18424467 2.97357418 4.20083785 5.36442491 6...
99  [2.18424467 2.97357418 4.20083785 5.36442491 6...

                                          light_curve
0   [{time: 0.0, band: 0, mag: 18.601379}; …] (120...
1   [{time: 0.0, band: 0, mag: 19.047684}; …] (120...
..                                                ...
98  [{time: 0.0, band: 0, mag: 19.9523}; …] (1200 ...
99  [{time: 0.0, band: 0, mag: 19.707044}; …] (120...

[100 rows x 7 columns]

Let's assign some random coordinates and create a catalog:

In [3]:
test_cat = lsdb.generate_catalog(len(df), 0)
test_cat_comp = test_cat.compute()
df["ra"] = test_cat_comp["ra"].to_numpy()
df["dec"] = test_cat_comp["dec"].to_numpy()

In [4]:
cat = lsdb.from_dataframe(df)
cat

Dask NestedFrame Structure:
                                 ID         cos_inc         log_mbh        log_mdot        redshift                             lag                                           light_curve               ra              dec
npartitions=12
0                    int64[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  list<element: double>[pyarrow]  nested<time: [double], band: [int64], mag: [double]>  double[pyarrow]  double[pyarrow]
288230376151711744              ...             ...             ...             ...             ...                             ...                                                   ...              ...              ...
...                             ...             ...             ...             ...             ...                             ...                                                   ...              ...              ...
3170534137668829184             ...             ...             ...             ...             ...                             ...                                                   ...              ...              ...
3458764513820540928             ...             ...             ...             ...             ...                             ...                                                   ...              ...              ...
Dask Name: astype, 4 expressions
Expr=AsType(frame=MapPartitions(NestedFrame), dtypes={'light_curve': nested<time: [double], band: [int64], mag: [double]>})

Let's use EzTaoX to run the fitting:

In [15]:
def initSampler(key):
    """Function to sample initial parameters"""
    k1, k2, k3, k4, k5 = jax.random.split(key, 5)

    # GP kernel param
    log_drw_scale = jax.random.uniform(k1, minval=jnp.log(0.01), maxval=jnp.log(1000))
    log_drw_sigma = jax.random.uniform(k2, minval=jnp.log(0.01), maxval=jnp.log(10))
    log_kernel_param = jnp.stack([log_drw_scale, log_drw_sigma])

    # parameters to relate the amplitudes in each band
    log_amp_scale = jax.random.uniform(k3, minval=-2.0, maxval=2.0)
    mean = jax.random.uniform(k4, shape=(2,), minval=-0.1, maxval=0.1)
    lag = jax.random.uniform(k5, minval=-10.0, maxval=10.0)

    return {
        "log_kernel_param": log_kernel_param,
        "log_amp_scale": log_amp_scale,
        "mean": mean,
        "lag": lag,
    }

In [16]:
SNR = 1000.0
global_key = jax.random.PRNGKey(1)


def run_eztaox(objid, time, band, mag):
    """Function to use within LSDB"""
    times, mags, noisy_mags, mag_errs = {}, {}, {}, {}
    bands = list(np.unique(band)[[0, -1]])
    for b in bands:
        mask = band == b
        times[b] = time[mask]
        mags[b] = mag[mask]
        noisy_mags[b] = (
            mags[b] + np.random.normal(0, 1, size=mags[b].shape) * mags[b] / SNR
        )
        mag_errs[b] = mags[b] / SNR
    inds = jnp.argsort(jnp.concatenate([times[b] for b in bands]))
    X = (
        jnp.concatenate([times[b] for b in bands])[inds],
        jnp.concatenate(
            [i * jnp.ones_like(times[b], dtype=int) for i, b in enumerate(bands)]
        )[inds],
    )
    for b in bands:
        noisy_mags[b] = jnp.array(noisy_mags[b])
        noisy_mags[b] -= jnp.median(noisy_mags[b])

    y = jnp.concatenate([noisy_mags[b] for b in bands])[inds]
    yerr = jnp.concatenate([mag_errs[b] for b in bands])[inds]

    has_lag = True  # if fit interband lags
    zero_mean = True  # if fit a mean function
    nBand = len(bands)

    # initialize a GP kernel, note the initial parameters are not used in the fitting
    k = Exp(scale=100.0, sigma=1.0)
    m = MultiVarModel(X, y, yerr, k, nBand, has_lag=has_lag, zero_mean=zero_mean)

    model = m
    nSample = 1_000
    nBest = 5  # it seems like this number needs to be high
    fit_key = jax.random.fold_in(global_key, objid)
    bestP, ll = random_search(model, initSampler, fit_key, nSample, nBest)

    return {"best_params": bestP, "log_likelihood": ll}

In [17]:
with Client(n_workers=4):
    res = cat.map_rows(
        run_eztaox,
        columns=["ID", "light_curve.time", "light_curve.band", "light_curve.mag"],
        row_container="args",
        meta={"best_params": "object", "log_likelihood": "float64"},
    ).compute()

In [18]:
res

,best_params,log_likelihood
_healpix_29,,
269542591213090035,"{'lag': 3.5237358202240063, 'log_amp_scale': 0.014695416381065245, 'log_kernel_param': [6.133698420610449, -0.3381998384992314], 'mean': [-0.08943050470935084, -0.0058232756726725125]}",627.3397507009403
240262208827197915,"{'lag': 4.453052939264413, 'log_amp_scale': -0.05040396726524184, 'log_kernel_param': [3.2298054131423153, -1.1201278505383714], 'mean': [-0.036421909795023, 0.07467187206357005]}",476.92709966495204
...,...,...
3301633586349654276,"{'lag': 4.4440122765229475, 'log_amp_scale': -0.037102894934129986, 'log_kernel_param': [4.713561512678283, -0.9592443395550467], 'mean': [-0.056000621247977514, 0.09788996416626752]}",619.1706349112964
3173577650530402769,"{'lag': 3.491311721991346, 'log_amp_scale': -0.12560952636460995, 'log_kernel_param': [2.8319716703523468, -1.4389142510219735], 'mean': [-0.03272840752296387, 0.0544989313253907]}",524.9203481173251